server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
#  - job_name: system-logs
 #   static_configs:
  #    - targets:
   #       - localhost
    #    labels:
     #     job: varlogs
      #    __path__: /var/log/*.log

  - job_name: nginx-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          __path__: /var/log/nginx/*.log
          
          
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'
      - source_labels: ['__meta_docker_container_id']
        target_label: 'container_id'
      - source_labels: ['__meta_docker_container_image']
        target_label: 'image'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: 'project'
      - replacement: /var/lib/docker/containers/*/*-json.log
        target_label: '__path__'

    pipeline_stages:
      - multiline:
          firstline: '^{'
          continuation: '^\s'
          max_wait_time: 3s
      - json:
          expressions:
            container: container
            container_id: container_id

